name: bip_hip
description: A new social app built with flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

#  `flutter pub upgrade --major-versions`
# `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0
  confetti: ^0.7.0
  dio: ^5.3.2
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  introduction_screen: ^3.1.11
  mask_text_input_formatter: ^2.5.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  get: ^4.6.5
  percent_indicator: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.7.2
  mime: ^1.0.4
  flutter_svg: ^2.0.7
  any_link_preview: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - .env
    - .env.dev
    - .env.example

  fonts:
    - family: BipHip
      fonts:
        - asset: assets/fonts/Icon_font/BipHip.ttf

    - family: BipHip2
      fonts:
        - asset: assets/fonts/Icon_font/BipHip2.ttf

    - family: BipHip3
      fonts:
        - asset: assets/fonts/Icon_font/BipHip3.ttf
