name: bip_hip
description: A new social app built with flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

#  `flutter pub upgrade --major-versions`
# `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0
  confetti: ^0.7.0
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  introduction_screen: ^3.1.11
  mask_text_input_formatter: ^2.5.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  get: ^4.6.5
  percent_indicator: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.7.2
  mime: ^1.0.4
  flutter_svg: ^2.0.7
  any_link_preview: ^3.0.1
  flutter_rating_bar: ^4.0.1
  timer_count_down: ^2.2.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  change_app_package_name: ^1.1.0
  flutter_facebook_auth: ^6.0.4
  flutter_reaction_button: ^3.0.0+3
  photo_view: ^0.14.0
  qr_flutter: ^4.1.0
  flutter_mentions: ^2.0.1
  linkfy_text: ^1.1.5
  socket_io_client: ^2.0.3+1
  peerdart: ^0.5.4
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - .env
    - .env.dev
    - .env.example

  fonts:
    - family: BipHip
      fonts:
        - asset: assets/fonts/Icon_font/BipHip.ttf

    - family: BipHip2
      fonts:
        - asset: assets/fonts/Icon_font/BipHip2.ttf

    - family: BipHip3
      fonts:
        - asset: assets/fonts/Icon_font/BipHip3.ttf

    - family: BipHip5
      fonts:
        - asset: assets/fonts/Icon_font/BipHip5.ttf

    - family: BipHip6
      fonts:
        - asset: assets/fonts/Icon_font/BipHip6.ttf

    - family: Chat
      fonts:
        - asset: assets/fonts/Icon_font/Chat.ttf